name: Combine PRs

on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        type: string
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
      mustBeGreen:
        type: boolean
        description: 'Only combine PRs that are green (status is success)'
        required: true
        default: true
      combineBranchName:
        type: string
        description: 'Name of the branch to combine PRs into'
        required: true
        default: 'combine-prs-branch'
      ignoreLabel:
        type: string
        description: 'Exclude PRs with this label'
        required: true
        default: 'nocombine'

jobs:
  combine_prs:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: maidata/combine-prs@main
        with:
          branchPrefix: ${{ inputs.branchPrefix }}
          mustBeGreen: ${{ inputs.mustBeGreen }}
          combineBranchName: ${{ inputs.combineBranchName }}
          ignoreLabel: ${{ inputs.ignoreLabel }}
