on:
  workflow_call:
    inputs:
      branchPrefix:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
      mustBeGreen:
        description: 'Only combine PRs that are green (status is success)'
        required: true
        default: 'true'
      combineBranchName:
        description: 'Name of the branch to combine PRs into'
        required: true
        default: 'combine-prs-branch'
      ignoreLabel:
        description: 'Exclude PRs with this label'
        required: true
        default: 'nocombine'

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: maidata/combine-prs@main
        with:
          branchPrefix: ${{ inputs.branchPrefix }}
          mustBeGreen: ${{ inputs.mustBeGreen }}
          combineBranchName: ${{ inputs.combineBranchName }}
          ignoreLabel: ${{ inputs.ignoreLabel }}
